version: "3" 
services:

  bookmedik_web:
    depends_on:
      - db
    container_name: bookmedik_app
    image: arp2092/bookmedik_php:v1
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - ENV_MYSQL_USER=bookmedik_user
      - ENV_MYSQL_PASSWORD=bookmedik_pass
      - DB_PORT_3306_TCP_ADDR=db
      - ENV_MYSQL_DATABASE=bookmedik
    volumes:
      - ./logs:/var/log/apache2

  db:
    image: mariadb:latest
    container_name: mariadb_bookmedik
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookmedik
      - MYSQL_USER=bookmedik_user
      - MYSQL_PASSWORD=bookmedik_pass
    volumes:
      - /home/adri/GitHub/docker_php/build/Tarea1/bookmedik/schema.sql:/docker-entrypoint-initdb.d/datadump.sql
      - ./database:/var/lib/mysql